apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-traffic-exporter
  namespace: monitoring
  labels:
    app: k8s-traffic-exporter
    release: prometheus
spec:
  selector:
    matchLabels:
      app: k8s-traffic-exporter
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
