apiVersion: v1
kind: Service
metadata:
  name: k8s-traffic-exporter
  namespace: monitoring
  labels:
    app: k8s-traffic-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9000
      targetPort: metrics
      protocol: TCP
  selector:
    app: k8s-traffic-exporter
